// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: svg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_svg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_svg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_svg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_svg_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_svg_2eproto;
namespace svg_serialize {
class Color;
struct ColorDefaultTypeInternal;
extern ColorDefaultTypeInternal _Color_default_instance_;
class Point;
struct PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
class Rgb;
struct RgbDefaultTypeInternal;
extern RgbDefaultTypeInternal _Rgb_default_instance_;
class Rgba;
struct RgbaDefaultTypeInternal;
extern RgbaDefaultTypeInternal _Rgba_default_instance_;
}  // namespace svg_serialize
PROTOBUF_NAMESPACE_OPEN
template<> ::svg_serialize::Color* Arena::CreateMaybeMessage<::svg_serialize::Color>(Arena*);
template<> ::svg_serialize::Point* Arena::CreateMaybeMessage<::svg_serialize::Point>(Arena*);
template<> ::svg_serialize::Rgb* Arena::CreateMaybeMessage<::svg_serialize::Rgb>(Arena*);
template<> ::svg_serialize::Rgba* Arena::CreateMaybeMessage<::svg_serialize::Rgba>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace svg_serialize {

// ===================================================================

class Point final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:svg_serialize.Point) */ {
 public:
  inline Point() : Point(nullptr) {}
  ~Point() override;
  explicit PROTOBUF_CONSTEXPR Point(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Point(const Point& from);
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point& operator=(Point&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Point& default_instance() {
    return *internal_default_instance();
  }
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }
  inline void Swap(Point* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Point* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Point& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Point& from) {
    Point::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "svg_serialize.Point";
  }
  protected:
  explicit Point(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // @@protoc_insertion_point(class_scope:svg_serialize.Point)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double x_;
    double y_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_svg_2eproto;
};
// -------------------------------------------------------------------

class Rgb final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:svg_serialize.Rgb) */ {
 public:
  inline Rgb() : Rgb(nullptr) {}
  ~Rgb() override;
  explicit PROTOBUF_CONSTEXPR Rgb(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Rgb(const Rgb& from);
  Rgb(Rgb&& from) noexcept
    : Rgb() {
    *this = ::std::move(from);
  }

  inline Rgb& operator=(const Rgb& from) {
    CopyFrom(from);
    return *this;
  }
  inline Rgb& operator=(Rgb&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Rgb& default_instance() {
    return *internal_default_instance();
  }
  static inline const Rgb* internal_default_instance() {
    return reinterpret_cast<const Rgb*>(
               &_Rgb_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Rgb& a, Rgb& b) {
    a.Swap(&b);
  }
  inline void Swap(Rgb* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Rgb* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Rgb* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Rgb>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Rgb& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Rgb& from) {
    Rgb::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rgb* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "svg_serialize.Rgb";
  }
  protected:
  explicit Rgb(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRFieldNumber = 1,
    kGFieldNumber = 2,
    kBFieldNumber = 3,
  };
  // uint32 r = 1;
  void clear_r();
  uint32_t r() const;
  void set_r(uint32_t value);
  private:
  uint32_t _internal_r() const;
  void _internal_set_r(uint32_t value);
  public:

  // uint32 g = 2;
  void clear_g();
  uint32_t g() const;
  void set_g(uint32_t value);
  private:
  uint32_t _internal_g() const;
  void _internal_set_g(uint32_t value);
  public:

  // uint32 b = 3;
  void clear_b();
  uint32_t b() const;
  void set_b(uint32_t value);
  private:
  uint32_t _internal_b() const;
  void _internal_set_b(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:svg_serialize.Rgb)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t r_;
    uint32_t g_;
    uint32_t b_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_svg_2eproto;
};
// -------------------------------------------------------------------

class Rgba final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:svg_serialize.Rgba) */ {
 public:
  inline Rgba() : Rgba(nullptr) {}
  ~Rgba() override;
  explicit PROTOBUF_CONSTEXPR Rgba(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Rgba(const Rgba& from);
  Rgba(Rgba&& from) noexcept
    : Rgba() {
    *this = ::std::move(from);
  }

  inline Rgba& operator=(const Rgba& from) {
    CopyFrom(from);
    return *this;
  }
  inline Rgba& operator=(Rgba&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Rgba& default_instance() {
    return *internal_default_instance();
  }
  static inline const Rgba* internal_default_instance() {
    return reinterpret_cast<const Rgba*>(
               &_Rgba_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Rgba& a, Rgba& b) {
    a.Swap(&b);
  }
  inline void Swap(Rgba* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Rgba* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Rgba* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Rgba>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Rgba& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Rgba& from) {
    Rgba::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rgba* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "svg_serialize.Rgba";
  }
  protected:
  explicit Rgba(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRFieldNumber = 1,
    kGFieldNumber = 2,
    kOFieldNumber = 4,
    kBFieldNumber = 3,
  };
  // uint32 r = 1;
  void clear_r();
  uint32_t r() const;
  void set_r(uint32_t value);
  private:
  uint32_t _internal_r() const;
  void _internal_set_r(uint32_t value);
  public:

  // uint32 g = 2;
  void clear_g();
  uint32_t g() const;
  void set_g(uint32_t value);
  private:
  uint32_t _internal_g() const;
  void _internal_set_g(uint32_t value);
  public:

  // double o = 4;
  void clear_o();
  double o() const;
  void set_o(double value);
  private:
  double _internal_o() const;
  void _internal_set_o(double value);
  public:

  // uint32 b = 3;
  void clear_b();
  uint32_t b() const;
  void set_b(uint32_t value);
  private:
  uint32_t _internal_b() const;
  void _internal_set_b(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:svg_serialize.Rgba)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t r_;
    uint32_t g_;
    double o_;
    uint32_t b_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_svg_2eproto;
};
// -------------------------------------------------------------------

class Color final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:svg_serialize.Color) */ {
 public:
  inline Color() : Color(nullptr) {}
  ~Color() override;
  explicit PROTOBUF_CONSTEXPR Color(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Color(const Color& from);
  Color(Color&& from) noexcept
    : Color() {
    *this = ::std::move(from);
  }

  inline Color& operator=(const Color& from) {
    CopyFrom(from);
    return *this;
  }
  inline Color& operator=(Color&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Color& default_instance() {
    return *internal_default_instance();
  }
  enum ColorCase {
    kStringColor = 2,
    kRgbColor = 3,
    kRgbaColor = 4,
    COLOR_NOT_SET = 0,
  };

  static inline const Color* internal_default_instance() {
    return reinterpret_cast<const Color*>(
               &_Color_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Color& a, Color& b) {
    a.Swap(&b);
  }
  inline void Swap(Color* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Color* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Color* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Color>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Color& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Color& from) {
    Color::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Color* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "svg_serialize.Color";
  }
  protected:
  explicit Color(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStringColorFieldNumber = 2,
    kRgbColorFieldNumber = 3,
    kRgbaColorFieldNumber = 4,
  };
  // string string_color = 2;
  bool has_string_color() const;
  private:
  bool _internal_has_string_color() const;
  public:
  void clear_string_color();
  const std::string& string_color() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_string_color(ArgT0&& arg0, ArgT... args);
  std::string* mutable_string_color();
  PROTOBUF_NODISCARD std::string* release_string_color();
  void set_allocated_string_color(std::string* string_color);
  private:
  const std::string& _internal_string_color() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_string_color(const std::string& value);
  std::string* _internal_mutable_string_color();
  public:

  // .svg_serialize.Rgb rgb_color = 3;
  bool has_rgb_color() const;
  private:
  bool _internal_has_rgb_color() const;
  public:
  void clear_rgb_color();
  const ::svg_serialize::Rgb& rgb_color() const;
  PROTOBUF_NODISCARD ::svg_serialize::Rgb* release_rgb_color();
  ::svg_serialize::Rgb* mutable_rgb_color();
  void set_allocated_rgb_color(::svg_serialize::Rgb* rgb_color);
  private:
  const ::svg_serialize::Rgb& _internal_rgb_color() const;
  ::svg_serialize::Rgb* _internal_mutable_rgb_color();
  public:
  void unsafe_arena_set_allocated_rgb_color(
      ::svg_serialize::Rgb* rgb_color);
  ::svg_serialize::Rgb* unsafe_arena_release_rgb_color();

  // .svg_serialize.Rgba rgba_color = 4;
  bool has_rgba_color() const;
  private:
  bool _internal_has_rgba_color() const;
  public:
  void clear_rgba_color();
  const ::svg_serialize::Rgba& rgba_color() const;
  PROTOBUF_NODISCARD ::svg_serialize::Rgba* release_rgba_color();
  ::svg_serialize::Rgba* mutable_rgba_color();
  void set_allocated_rgba_color(::svg_serialize::Rgba* rgba_color);
  private:
  const ::svg_serialize::Rgba& _internal_rgba_color() const;
  ::svg_serialize::Rgba* _internal_mutable_rgba_color();
  public:
  void unsafe_arena_set_allocated_rgba_color(
      ::svg_serialize::Rgba* rgba_color);
  ::svg_serialize::Rgba* unsafe_arena_release_rgba_color();

  void clear_color();
  ColorCase color_case() const;
  // @@protoc_insertion_point(class_scope:svg_serialize.Color)
 private:
  class _Internal;
  void set_has_string_color();
  void set_has_rgb_color();
  void set_has_rgba_color();

  inline bool has_color() const;
  inline void clear_has_color();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ColorUnion {
      constexpr ColorUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr string_color_;
      ::svg_serialize::Rgb* rgb_color_;
      ::svg_serialize::Rgba* rgba_color_;
    } color_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_svg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Point

// double x = 1;
inline void Point::clear_x() {
  _impl_.x_ = 0;
}
inline double Point::_internal_x() const {
  return _impl_.x_;
}
inline double Point::x() const {
  // @@protoc_insertion_point(field_get:svg_serialize.Point.x)
  return _internal_x();
}
inline void Point::_internal_set_x(double value) {
  
  _impl_.x_ = value;
}
inline void Point::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:svg_serialize.Point.x)
}

// double y = 2;
inline void Point::clear_y() {
  _impl_.y_ = 0;
}
inline double Point::_internal_y() const {
  return _impl_.y_;
}
inline double Point::y() const {
  // @@protoc_insertion_point(field_get:svg_serialize.Point.y)
  return _internal_y();
}
inline void Point::_internal_set_y(double value) {
  
  _impl_.y_ = value;
}
inline void Point::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:svg_serialize.Point.y)
}

// -------------------------------------------------------------------

// Rgb

// uint32 r = 1;
inline void Rgb::clear_r() {
  _impl_.r_ = 0u;
}
inline uint32_t Rgb::_internal_r() const {
  return _impl_.r_;
}
inline uint32_t Rgb::r() const {
  // @@protoc_insertion_point(field_get:svg_serialize.Rgb.r)
  return _internal_r();
}
inline void Rgb::_internal_set_r(uint32_t value) {
  
  _impl_.r_ = value;
}
inline void Rgb::set_r(uint32_t value) {
  _internal_set_r(value);
  // @@protoc_insertion_point(field_set:svg_serialize.Rgb.r)
}

// uint32 g = 2;
inline void Rgb::clear_g() {
  _impl_.g_ = 0u;
}
inline uint32_t Rgb::_internal_g() const {
  return _impl_.g_;
}
inline uint32_t Rgb::g() const {
  // @@protoc_insertion_point(field_get:svg_serialize.Rgb.g)
  return _internal_g();
}
inline void Rgb::_internal_set_g(uint32_t value) {
  
  _impl_.g_ = value;
}
inline void Rgb::set_g(uint32_t value) {
  _internal_set_g(value);
  // @@protoc_insertion_point(field_set:svg_serialize.Rgb.g)
}

// uint32 b = 3;
inline void Rgb::clear_b() {
  _impl_.b_ = 0u;
}
inline uint32_t Rgb::_internal_b() const {
  return _impl_.b_;
}
inline uint32_t Rgb::b() const {
  // @@protoc_insertion_point(field_get:svg_serialize.Rgb.b)
  return _internal_b();
}
inline void Rgb::_internal_set_b(uint32_t value) {
  
  _impl_.b_ = value;
}
inline void Rgb::set_b(uint32_t value) {
  _internal_set_b(value);
  // @@protoc_insertion_point(field_set:svg_serialize.Rgb.b)
}

// -------------------------------------------------------------------

// Rgba

// uint32 r = 1;
inline void Rgba::clear_r() {
  _impl_.r_ = 0u;
}
inline uint32_t Rgba::_internal_r() const {
  return _impl_.r_;
}
inline uint32_t Rgba::r() const {
  // @@protoc_insertion_point(field_get:svg_serialize.Rgba.r)
  return _internal_r();
}
inline void Rgba::_internal_set_r(uint32_t value) {
  
  _impl_.r_ = value;
}
inline void Rgba::set_r(uint32_t value) {
  _internal_set_r(value);
  // @@protoc_insertion_point(field_set:svg_serialize.Rgba.r)
}

// uint32 g = 2;
inline void Rgba::clear_g() {
  _impl_.g_ = 0u;
}
inline uint32_t Rgba::_internal_g() const {
  return _impl_.g_;
}
inline uint32_t Rgba::g() const {
  // @@protoc_insertion_point(field_get:svg_serialize.Rgba.g)
  return _internal_g();
}
inline void Rgba::_internal_set_g(uint32_t value) {
  
  _impl_.g_ = value;
}
inline void Rgba::set_g(uint32_t value) {
  _internal_set_g(value);
  // @@protoc_insertion_point(field_set:svg_serialize.Rgba.g)
}

// uint32 b = 3;
inline void Rgba::clear_b() {
  _impl_.b_ = 0u;
}
inline uint32_t Rgba::_internal_b() const {
  return _impl_.b_;
}
inline uint32_t Rgba::b() const {
  // @@protoc_insertion_point(field_get:svg_serialize.Rgba.b)
  return _internal_b();
}
inline void Rgba::_internal_set_b(uint32_t value) {
  
  _impl_.b_ = value;
}
inline void Rgba::set_b(uint32_t value) {
  _internal_set_b(value);
  // @@protoc_insertion_point(field_set:svg_serialize.Rgba.b)
}

// double o = 4;
inline void Rgba::clear_o() {
  _impl_.o_ = 0;
}
inline double Rgba::_internal_o() const {
  return _impl_.o_;
}
inline double Rgba::o() const {
  // @@protoc_insertion_point(field_get:svg_serialize.Rgba.o)
  return _internal_o();
}
inline void Rgba::_internal_set_o(double value) {
  
  _impl_.o_ = value;
}
inline void Rgba::set_o(double value) {
  _internal_set_o(value);
  // @@protoc_insertion_point(field_set:svg_serialize.Rgba.o)
}

// -------------------------------------------------------------------

// Color

// string string_color = 2;
inline bool Color::_internal_has_string_color() const {
  return color_case() == kStringColor;
}
inline bool Color::has_string_color() const {
  return _internal_has_string_color();
}
inline void Color::set_has_string_color() {
  _impl_._oneof_case_[0] = kStringColor;
}
inline void Color::clear_string_color() {
  if (_internal_has_string_color()) {
    _impl_.color_.string_color_.Destroy();
    clear_has_color();
  }
}
inline const std::string& Color::string_color() const {
  // @@protoc_insertion_point(field_get:svg_serialize.Color.string_color)
  return _internal_string_color();
}
template <typename ArgT0, typename... ArgT>
inline void Color::set_string_color(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_string_color()) {
    clear_color();
    set_has_string_color();
    _impl_.color_.string_color_.InitDefault();
  }
  _impl_.color_.string_color_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:svg_serialize.Color.string_color)
}
inline std::string* Color::mutable_string_color() {
  std::string* _s = _internal_mutable_string_color();
  // @@protoc_insertion_point(field_mutable:svg_serialize.Color.string_color)
  return _s;
}
inline const std::string& Color::_internal_string_color() const {
  if (_internal_has_string_color()) {
    return _impl_.color_.string_color_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void Color::_internal_set_string_color(const std::string& value) {
  if (!_internal_has_string_color()) {
    clear_color();
    set_has_string_color();
    _impl_.color_.string_color_.InitDefault();
  }
  _impl_.color_.string_color_.Set(value, GetArenaForAllocation());
}
inline std::string* Color::_internal_mutable_string_color() {
  if (!_internal_has_string_color()) {
    clear_color();
    set_has_string_color();
    _impl_.color_.string_color_.InitDefault();
  }
  return _impl_.color_.string_color_.Mutable(      GetArenaForAllocation());
}
inline std::string* Color::release_string_color() {
  // @@protoc_insertion_point(field_release:svg_serialize.Color.string_color)
  if (_internal_has_string_color()) {
    clear_has_color();
    return _impl_.color_.string_color_.Release();
  } else {
    return nullptr;
  }
}
inline void Color::set_allocated_string_color(std::string* string_color) {
  if (has_color()) {
    clear_color();
  }
  if (string_color != nullptr) {
    set_has_string_color();
    _impl_.color_.string_color_.InitAllocated(string_color, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:svg_serialize.Color.string_color)
}

// .svg_serialize.Rgb rgb_color = 3;
inline bool Color::_internal_has_rgb_color() const {
  return color_case() == kRgbColor;
}
inline bool Color::has_rgb_color() const {
  return _internal_has_rgb_color();
}
inline void Color::set_has_rgb_color() {
  _impl_._oneof_case_[0] = kRgbColor;
}
inline void Color::clear_rgb_color() {
  if (_internal_has_rgb_color()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.color_.rgb_color_;
    }
    clear_has_color();
  }
}
inline ::svg_serialize::Rgb* Color::release_rgb_color() {
  // @@protoc_insertion_point(field_release:svg_serialize.Color.rgb_color)
  if (_internal_has_rgb_color()) {
    clear_has_color();
    ::svg_serialize::Rgb* temp = _impl_.color_.rgb_color_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.color_.rgb_color_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::svg_serialize::Rgb& Color::_internal_rgb_color() const {
  return _internal_has_rgb_color()
      ? *_impl_.color_.rgb_color_
      : reinterpret_cast< ::svg_serialize::Rgb&>(::svg_serialize::_Rgb_default_instance_);
}
inline const ::svg_serialize::Rgb& Color::rgb_color() const {
  // @@protoc_insertion_point(field_get:svg_serialize.Color.rgb_color)
  return _internal_rgb_color();
}
inline ::svg_serialize::Rgb* Color::unsafe_arena_release_rgb_color() {
  // @@protoc_insertion_point(field_unsafe_arena_release:svg_serialize.Color.rgb_color)
  if (_internal_has_rgb_color()) {
    clear_has_color();
    ::svg_serialize::Rgb* temp = _impl_.color_.rgb_color_;
    _impl_.color_.rgb_color_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Color::unsafe_arena_set_allocated_rgb_color(::svg_serialize::Rgb* rgb_color) {
  clear_color();
  if (rgb_color) {
    set_has_rgb_color();
    _impl_.color_.rgb_color_ = rgb_color;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:svg_serialize.Color.rgb_color)
}
inline ::svg_serialize::Rgb* Color::_internal_mutable_rgb_color() {
  if (!_internal_has_rgb_color()) {
    clear_color();
    set_has_rgb_color();
    _impl_.color_.rgb_color_ = CreateMaybeMessage< ::svg_serialize::Rgb >(GetArenaForAllocation());
  }
  return _impl_.color_.rgb_color_;
}
inline ::svg_serialize::Rgb* Color::mutable_rgb_color() {
  ::svg_serialize::Rgb* _msg = _internal_mutable_rgb_color();
  // @@protoc_insertion_point(field_mutable:svg_serialize.Color.rgb_color)
  return _msg;
}

// .svg_serialize.Rgba rgba_color = 4;
inline bool Color::_internal_has_rgba_color() const {
  return color_case() == kRgbaColor;
}
inline bool Color::has_rgba_color() const {
  return _internal_has_rgba_color();
}
inline void Color::set_has_rgba_color() {
  _impl_._oneof_case_[0] = kRgbaColor;
}
inline void Color::clear_rgba_color() {
  if (_internal_has_rgba_color()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.color_.rgba_color_;
    }
    clear_has_color();
  }
}
inline ::svg_serialize::Rgba* Color::release_rgba_color() {
  // @@protoc_insertion_point(field_release:svg_serialize.Color.rgba_color)
  if (_internal_has_rgba_color()) {
    clear_has_color();
    ::svg_serialize::Rgba* temp = _impl_.color_.rgba_color_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.color_.rgba_color_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::svg_serialize::Rgba& Color::_internal_rgba_color() const {
  return _internal_has_rgba_color()
      ? *_impl_.color_.rgba_color_
      : reinterpret_cast< ::svg_serialize::Rgba&>(::svg_serialize::_Rgba_default_instance_);
}
inline const ::svg_serialize::Rgba& Color::rgba_color() const {
  // @@protoc_insertion_point(field_get:svg_serialize.Color.rgba_color)
  return _internal_rgba_color();
}
inline ::svg_serialize::Rgba* Color::unsafe_arena_release_rgba_color() {
  // @@protoc_insertion_point(field_unsafe_arena_release:svg_serialize.Color.rgba_color)
  if (_internal_has_rgba_color()) {
    clear_has_color();
    ::svg_serialize::Rgba* temp = _impl_.color_.rgba_color_;
    _impl_.color_.rgba_color_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Color::unsafe_arena_set_allocated_rgba_color(::svg_serialize::Rgba* rgba_color) {
  clear_color();
  if (rgba_color) {
    set_has_rgba_color();
    _impl_.color_.rgba_color_ = rgba_color;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:svg_serialize.Color.rgba_color)
}
inline ::svg_serialize::Rgba* Color::_internal_mutable_rgba_color() {
  if (!_internal_has_rgba_color()) {
    clear_color();
    set_has_rgba_color();
    _impl_.color_.rgba_color_ = CreateMaybeMessage< ::svg_serialize::Rgba >(GetArenaForAllocation());
  }
  return _impl_.color_.rgba_color_;
}
inline ::svg_serialize::Rgba* Color::mutable_rgba_color() {
  ::svg_serialize::Rgba* _msg = _internal_mutable_rgba_color();
  // @@protoc_insertion_point(field_mutable:svg_serialize.Color.rgba_color)
  return _msg;
}

inline bool Color::has_color() const {
  return color_case() != COLOR_NOT_SET;
}
inline void Color::clear_has_color() {
  _impl_._oneof_case_[0] = COLOR_NOT_SET;
}
inline Color::ColorCase Color::color_case() const {
  return Color::ColorCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace svg_serialize

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_svg_2eproto
